# Generated by Django 5.0.2 on 2024-03-21 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
