# Generated by Django 5.0.2 on 2024-03-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='table_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
